name: release httpctrl

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Run multi-line script
      env:
        HTTPCTRL_USERNAME: ${{ secrets.HTTPCTRL_USERNAME }}
        HTTPCTRL_PASSWORD: ${{ secrets.HTTPCTRL_PUBLISH_DOCUMENTATION }}
        HTTPCTRL_EMAIL: ${{ secrets.HTTPCTRL_EMAIL }}
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.HTTPCTRL_PYPI_API_TOKEN }}
      shell: bash
      run: ci/github-ci-docs.sh

